### ISSUE TITLE
Anakin Theme VSCODE!. 

### ISSUE THREAD

**Issue by balajin96** [laporeon/meliscraper#4]
Hi, 
 I know this is un related question to meliscraper.
 but i need to know!.

Did you developed this Anakin theme?. 

I need to **re-Install** it in my vsCode. but it is not showing in the "Extensions". can you help me out. 

![anakin](https://github.com/laporeon/meliscraper/assets/43362896/75050546-b241-41d3-94b5-357b04e1a3a0)

**Comment by laporeon** [comment]
Yes, I need. But the theme isn't available anymore, that's why you aren't being able to reinstall it. Thanks for your interest.
